call_center_task:
  description: >
    Receive an athlete’s inquiry about training, coaching availability,
    or program details via the Sports App chat.
    Gather key details (athlete_id, goals, preferred times, sport discipline),
    provide an empathetic welcome, and determine if the request must be escalated.
  expected_output: >
    • A friendly acknowledgement message to the athlete  
    • A structured intake payload:
      - athlete_id  
      - inquiry_summary  
      - collected_data (goals, times, discipline)  
    • Escalation flag: true/false
  agent: call_center_agent

backoffice_ops_task:
  description: >
    Validate the escalated request for session scheduling or program enrollment.
    Check coach availability, facility capacity, and admin permissions.
    Execute the approved CRUD operation (e.g., create/update/delete session or enrollment).
  expected_output: >
    • Feasibility verdict: “approved” or “rejected”  
    • Details of the performed action:
      - session_id  
      - coach_id  
      - scheduled_time  
      - resource_allocated  
    • Notes for call_center_agent on next steps
  agent: backoffice_ops_agent

team_lead_task:
  description: >
    Review the planned session or enrollment outcome for compliance with training guidelines,
    coach certifications, and program policies.
    Ensure the packaged response is accurate and ready to notify athlete and coach.
  expected_output: >
    • Approval status: “approved” or “needs_revision”  
    • Annotated feedback or required corrections  
    • Final go‑ahead flag for notification dispatch
  agent: team_lead_agent
